server:
  port: 8040

spring:
  application:
    name: product-service
    # MySQL
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flash-sale?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
  # Nacos
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  # redis
  data:
    redis:
      host: 192.168.182.128
      port: 6379
      password: 123456
      database: 0
  # RabbitMQ
  rabbitmq:
    host: 192.168.182.128
    port: 5672
    virtual-host: /
    username: qiu
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          multiplier: 2

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    org.qiu: debug