server:
  port:
    8000

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: 192.168.182.128
      port: 6379
      password: 123456
      database: 0
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "GET,POST,PUT,DELETE"
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          enabled: true # 让 gateway 可以发现 nacos 中的微服务
      routes:
        - id: snowflake
          uri: lb://snowflake-id-generate
          predicates:
            - Path=/snowflake/**
        - id: store
          uri: lb://store-service
          predicates:
            - Path=/store/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: reservation
          uri: lb://reservation-service
          predicates:
            - Path=/reservation/**
        - id: activity
          uri: lb://activity-service
          predicates:
            - Path=/activity/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**