server:
  port: 8060

spring:
  application:
    name: activity-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flash-sale?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: mysql
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl